version: '2'
services:
  centos6:
    image: centos_gcc:6
    build: ./centos6
    hostname: centos6
    tty: true
    volumes:
      - './centos6/home/:/home/:rw'
      - './centos6/opt/gcc-8.3.0/:/opt/gcc-8.3.0/:rw'
      - '../scripts/:/opt/gcc-8.3.0/workspace/scripts/:rw'
      - '../archives/:/opt/gcc-8.3.0/workspace/archives/:rw'
  ubuntu1604:
    image: ubuntu_gcc:16.04
    build: ./ubuntu1604
    hostname: ubuntu1604
    tty: true
    volumes:
      - './ubuntu1604/home/:/home/:rw'
      - './ubuntu1604/opt/gcc-8.3.0/:/opt/gcc-8.3.0/:rw'
      - '../scripts/:/opt/gcc-8.3.0/workspace/scripts/:rw'
      - '../archives/:/opt/gcc-8.3.0/workspace/archives/:rw'
